logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    com.omar.bookingappback: INFO

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: booking-app
  liquibase:
    contexts: prod
    default-schema: booking-app